### ISSUE TITLE
The polarity in D1 D2 D3 and D5 in sch is incorrect, but in pcb is correct

### ISSUE THREAD

**Issue by danieljpb** [Protocentral/AFE4490_Oximeter#1]
The polarity in D1 D2 D3 and D5 in sch is incorrect, but in brd is correct
![d1d2d3d5](https://cloud.githubusercontent.com/assets/3197644/15961771/f5e9ce84-2f06-11e6-8c4f-442bdff189f6.png)

**Comment by awhitchurch** [comment]
Yes, we are correcting this in the new version.
