### ISSUE TITLE
How is this different from the MAX30102 ? 

### ISSUE THREAD

**Issue by kiranshashiny** [Protocentral/AFE4490_Oximeter#12]

**Comment by MohammedHM** [comment]
Dear Kiran,


Afe4490 | MAX30102
-- | --
Manufactured by Texas Instrument | Manufactured by Maxim Integrated
Fully-Integrated Analog Front-End | SoC (System on a Chip)

Afe4400 has 24 bit ADC and HIGH resolution compared to MAX30102.

Regards,
Mohammed Ibrahim

**Comment by kiranshashiny** [comment]
Thanks,
